# Generated by Django 4.0.5 on 2022-06-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=200)),
                ('Image', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='itmes',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itmes',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
